auth_enabled: ${auth_enabled}

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  max_transfer_retries: 1

schema_config:
  configs:
  - from: 2018-04-15
    store: cassandra
    object_store: cassandra
    schema: v11
    index:
      prefix: cassandra_index_
      period: 168h
    chunks:
      prefix: cassandra_chunk_
      period: 168h
storage_config:
  cassandra:
    username: cassandra
    password: cassandra
    addresses: ${cassandra}
    auth: false
    keyspace: loki

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h

table_manager:
  retention_deletes_enabled: true
  retention_period: 336h

ruler:
  alertmanager_url: ${alertmanager_url}
  enable_alertmanager_v2: true
  enable_api: true
  enable_sharding: false
  evaluation_interval: 5s
  ring:
    kvstore:
      store: inmemory
  rule_path: /dev/shm/rules
  storage:
    type: local
    local:
      directory: /loki/rules
  ruler_client:
    tls_insecure_skip_verify: true
